STATION_METALS_CONFIG = {
    'STATION_1': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_2': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_3': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_4': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_5': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_6': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_7': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_8': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_9': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_10': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_11': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_12': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_13': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_14': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_15': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_16': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_17': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_18': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_19': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_20': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_21': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_22': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_24': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_25': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_26': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_27': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_28': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_29': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_30': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_31': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_32': {
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_33': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_34': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_35': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_36': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_37': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_38': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_39': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_40': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_41': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_42': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_43': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_44': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_45': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_46': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_47': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_48': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_49': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_50': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_51': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_52': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_53': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_54': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_55': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_56': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_57': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_58': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_59': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
    'STATION_60': {
        'Mercury': {'max_allowed': 0.005, 'alert_level': 'High'},
        'Cadmium': {'max_allowed': 0.01, 'alert_level': 'Medium'},
        'Lead': {'max_allowed': 0.05, 'alert_level': 'Low'},
        'Arsenic': {'max_allowed': 0.02, 'alert_level': 'High'},
        'Chromium': {'max_allowed': 0.05, 'alert_level': 'Low'},
    },
}
