STATION_ORGANIC_CONFIG = {
    'STATION_61': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_62': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_63': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_64': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_65': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_66': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_67': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_68': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_69': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_70': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_71': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_72': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_73': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_74': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_75': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_76': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_77': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_78': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_79': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_80': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_81': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_82': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_83': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_84': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_85': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_86': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_87': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_88': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_89': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_90': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_91': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_92': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_93': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_94': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_95': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_96': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_97': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_98': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
    'STATION_99': {
        'COD': {'optimal': 2.0, 'critical': 4.0},
        'BOD5': {'optimal': 1.0, 'critical': 3.0},
        'Ammonia': {'optimal': 0.05, 'critical': 0.1},
        'Phosphate': {'optimal': 0.01, 'critical': 0.05},
    },
}
